<?php
$this->widget('zii.widgets.CDetailView', array(
    'data' => $model,
    'attributes' => array(
        //'id_propuesta',
        array('name' => 'id_propuesta_padre',
            'type'=>'raw',
            'value' => CHtml::link('Ver', array('view', 'id' => $model->id_propuesta_padre,)),
            'visible' => $model->id_propuesta_padre ? true : false),
        array('name' => 'id_proceso',
            'value'=>$model->idProceso->titulo,
            'visible' => $model->idProceso->titulo ? true : false),
        array('name' => 'titulo',
            'type' => 'raw',
        ), array('name' => 'descripcion',
            'type' => 'raw',
        ),
        array('name' => 'estado',
            'value' => $model->estado0->nombre,
           // 'value'=>'<img align="middle" title="'.$model->estado0->nombre.'" src="' . Yii::app()->request->baseUrl . '/images/inc_est_propuesta/'.$model->estado.'.png"/>',
            'type'=>'raw'
        ),
        'cant_participantes',
        array('name' => 'Participantes',
            'type' => 'raw',
            'value' => $tabla),
        array('name' => 'usuario_creador',
            'value' => $model->usuarioCreador->nombre . ' ' . $model->usuarioCreador->apellido),
        'fecha_creacion',
        array('name' => 'fecha_presenta_propuesta',
            'visible' => $model->fecha_presenta_propuesta ? true : false),
        array('name' => 'fecha_resolucion',
            'visible' => $model->fecha_resolucion ? true : false),
        array('name' => 'fecha_resolucion_presentacion',
            'visible' => $model->fecha_resolucion_presentacion ? true : false),
        array('name' => 'estado_presentacion',
            'value' => $model->estadoPresentacion ? $model->estadoPresentacion->nombre : '',
            'visible' => $model->estado_presentacion ? true : false),
        array('name' => 'fecha_presentacion',
            'visible' => $model->fecha_presentacion ? true : false),
       
    ),
));
?>
